-keep public class * extends ir.ayantech.whygoogle.** { *; }
-keepclassmembernames class androidx.recyclerview.widget.RecyclerView { *; }
-keepclassmembers class androidx.recyclerview.widget.RecyclerView { *; }